apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-receiver-service
spec:
  selector:
    app: rabbitmq-receiver
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined
  template:
    metadata:
      labels:
        app: combined
    spec:
      containers:
        - name: rabbitmq-receiver-container
          image: lsnow987/rabbitmq-receiver:v4
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "your-erlang-cookie"
          volumeMounts:
            - name: video-volume
              mountPath: /home/lsnow/video_to_process
        - name: aws-file-downloader-container
          image: your-aws-file-downloader-image:tag
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "your-access-key-id"
            - name: AWS_SECRET_ACCESS_KEY
              value: "your-secret-access-key"
            - name: AWS_DEFAULT_REGION
              value: "your-region"
          volumeMounts:
            - name: upload-volume
              mountPath: /home/lsnow/upload
      volumes:
        - name: video-volume
          hostPath:
            path: /home/lsnow/video_to_process
        - name: upload-volume
          hostPath:
            path: /home/lsnow/upload
