apiVersion: v1
kind: Service
metadata:
  name: docker-java-jar-service
spec:
  selector:
    app: docker-java-jar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5672
    - protocol: TCP
      port: 8080
      targetPort: 15672
  type: LoadBalancer
